App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^index2/$', views.index2, name='index2'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^goods/(\w+)/$', views.goods, name='goods'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^quit/$', views.quit, name='quit'),
    url(r'^checkin/$', views.checkin, name='checkin'),
    # url(r'^checkon/$', views.checkon, name='checkon'),
    url(r'^addcart/$', views.addcart, name='addcart'),  # 添加商品操作
    url(r'^subcart/$', views.subcart, name='subcart'),  # 删减商品操作
    url(r'^changecartstatus/$', views.changecartstatus, name='changecartstatus'),  # 修改选中状态
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),  # 全选/取消全选

    url(r'^generateorder/$', views.generateorder, name='generateorder'),  # 下单
    url(r'^orderinfo/(\d+)/$', views.orderinfo, name='orderinfo'),

    url(r'^pay/$', views.pay, name='pay'),  # 支付
    url(r'^notifyurl/$', views.notifyurl, name='notifyurl'),  # 支付完成后的通知
    url(r'^returnurl/$', views.returnurl, name='returnurl'),  # 支付完成后的跳转

]

django02/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^meilihui/', include('App.urls', namespace='App')),
    url(r'^meilihui/', include('App.urls', namespace='App'))
]

App/models.py
from django.db import models

# Create your models here.

class Wheel(models.Model):
    # 图片
    img = models.CharField(max_length=100)
    # 名称
    name = models.CharField(max_length=100)

class Goodslist(models.Model):
    # "id": "product1",
    # "buyer": "买手推荐",
    # "src1": "'/static/img/product1_1.jpg'",
    # "src2": "'/static/img/product1_2.jpg'",
    # "src3": "'/static/img/product1_3.jpg'",
    # "title": "红色荔枝纹拉链手提肩包",
    # "name": "Tory Burch",
    # "price": "￥2,440 ",
    # "original_price": "￥4,880",
    # "index1": "'/static/img/product1_1_s.jpg'",
    # "index2": "'/static/img/product1_2_s.jpg'",
    # "index3": "'/static/img/product1_3_s.jpg'"
    goodsid=models.CharField(max_length=20)
    buyer=models.CharField(max_length=20)
    src1=models.CharField(max_length=100)
    src2=models.CharField(max_length=100)
    src3=models.CharField(max_length=100)
    title=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    price=models.CharField(max_length=40)
    original_price=models.CharField(max_length=40)
    index1=models.CharField(max_length=100)
    index2=models.CharField(max_length=100)
    index3=models.CharField(max_length=100)


class Goodsdetail(models.Model):
    goodsid = models.CharField(max_length=20)
    buyer = models.CharField(max_length=20)
    src1 = models.CharField(max_length=100)
    src2 = models.CharField(max_length=100)
    src3 = models.CharField(max_length=100)
    src4 = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    original_price = models.DecimalField(max_digits=7, decimal_places=2)
    index1 = models.CharField(max_length=100)
    index2 = models.CharField(max_length=100)
    index3 = models.CharField(max_length=100)
    index4 = models.CharField(max_length=100)


class User(models.Model):
    tel = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=256)


class Cart(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 商品
    goods = models.ForeignKey(Goodsdetail)
    # 商品数量(选择)
    number = models.IntegerField()
    # 是否选中
    isselect = models.BooleanField(default=True)


# 订单
# 一个用户 对应 多个订单
# 在从表这声明关系
# 状态
# -1 过期
# 1 未付款
# 2 已付款，未发货
# 3 已发货，快递
# 4 已签收，未评价
# 5 已评价
# 6 退款....
class Order(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 创建时间
    createtime = models.DateTimeField(auto_now_add=True)

    status = models.IntegerField(default=1)
    # 订单号
    identifier = models.CharField(max_length=256)

# 订单商品
# 一个订单 对应 多个商品
# 在从表中声明关系
class OrderGoods(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    goods = models.ForeignKey(Goodsdetail)
    # 个数
    number = models.IntegerField(default=1)

    # 大小
    # 颜色

templates/index2.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		<meta charset="utf-8" />
		<title>Tory Burch女士精品系列上新-Tory Burch官网-Tory Burch折扣—尽在魅力惠官网</title>
		<link rel="icon" href="{% static 'img/love.png' %}" type="image/x-icon">
		<link rel="stylesheet" href="{% static 'css/header-footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/index2.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/header-footer.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/index2.js' %}" ></script>

	</head>
	<body>
		<div class="login">
			<div class="header">
				<ul class="header_left">
					{% if tel %}
						<li>
							<img src="{% static 'img/zhuceyouli.gif' %}">
							<a href="{% url 'App:register' %}" target="_blank">{{ tel }}</a>
						</li>
						<li>|</li>
						<li><a href="/meilihui/quit/" target="_blank"> 退出 </a></li>
						<li>|</li>
<<<<<<< HEAD
                        <li><a href="/meilihui/cart/" target="_blank"> 购物车 </a></li>
=======
                        <li><a href="/cart/" target="_blank"> 购物车 </a></li>
>>>>>>> 751228054eba81cee58bef5ac28ffb243a135039
					{% else %}
						<li>
							<img src="{% static 'img/zhuceyouli.gif' %}">
							<a href="{% url 'App:register' %}" target="_blank">注册有礼</a>
						</li>
						<li>|</li>
						<li><a href="{% url 'App:login' %}" target="_blank">登录</a></li>

					{% endif %}


				</ul>
				<ul class="header_right">
					<li><a href="#" >在线咨询</a></li>
					<li>|</li>
					<li style="position: relative;">
						<a href="http://www.mei.com/mobile" >手机版</a>
						<div class="download">
							<img src="../static/img/side_middle1.png" />
							<p>扫码下载APP</p>
						</div>
					</li>
					<li>|</li>
					<li><a href="http://weibo.com/glamoursaleschina?spm=a2o1p.8183483.0.0.fQlt7u" ></a></li>
				</ul>
			</div>
		</div>
		<div class="logo">
			<a href="index.html"></a>
			<a href="index.html"></a>
		</div>
		<div class="nav">
			<div class="list">
				<ul class="list_left">
					<li><a href="{% url 'App:index' %}">首页</a></li>
					<li>
						<a href="#">女士</a>
						<div class="smallnav">
							<div class="smallnav_left">
								<h4>热门活动</h4>
								<ul>
									<li><a href="#">买手精选 设计师连衣裙专场</a></li>
									<li><a href="#">买手精选 设计师品牌服装</a></li>
									<li><a href="#">买手精选 设计师包袋配饰</a></li>
									<li><a href="#">上海时装周 设计师品牌专场（满减）</a></li>
									<li><a href="#">上海时装周 JANE EYRE专场（满减）</a></li>
									<li><a href="#">LACOSTE 女鞋</a></li>
									<li><a href="#">RUCOLINE 意式休闲时尚女鞋</a></li>
									<li><a href="#">MO&Co. 90S极简时髦女装</a></li>
								</ul>
								<p><a href="#" class="look">查看所有活动</a></p>
							</div>
							<div class="smallnav_right">
								<h4>商品分类</h4>
								<ul>
									<li><a href="#">配饰</a></li>
									<li><a href="#">服装</a></li>
									<li><a href="#">鞋履</a></li>
									<li><a href="#">包袋</a></li>
									<li><a href="#">手表&首饰</a></li>
									<li><a href="#">眼镜</a></li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<a href="#">男士</a>
						<div class="smallnav">
							<div class="smallnav_left">
								<h4>热门活动</h4>
								<ul>
									<li><a href="#">LACOSTE 男鞋</a></li>
									<li><a href="#">奢华男士 多品牌鞋履配饰</a></li>
									<li><a href="#">INITIAL  轻剪裁男装及配饰</a></li>
									<li><a href="#">VIKTOR & ROLF 剑走偏锋的时尚艺术男士</a></li>
									<li><a href="#">COSTUME N COSTUME 简洁精致男士</a></li>
									<li><a href="#">SKECHERS 男鞋</a></li>
									<li><a href="#">LOTTUSSE 匠心工艺 典藏男士鞋包</a></li>
									<li><a href="#">PAUL& SHARK  闲适优雅 格调男装</a></li>
								</ul>
								<p><a href="#" class="look">查看所有活动</a></p>
							</div>
							<div class="smallnav_right">
								<h4>商品分类</h4>
								<ul>
									<li><a href="#">配饰</a></li>
									<li><a href="#">鞋履</a></li>
									<li><a href="#">服装</a></li>
									<li><a href="#">眼镜</a></li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<a href="#">美妆</a>
						<div class="smallnav">
							<div class="smallnav_left">
								<h4>热门活动</h4>
								<ul>
									<li><a href="#">FRESH 馥蕾诗护肤品专场</a></li>
									<li><a href="#">ALBION 澳尔滨护肤品专场</a></li>
									<li><a href="#">CLE DE PEAU BEAUTE 肌肤之钥高端护肤彩妆</a></li>
									<li><a href="#">The HISTORY OF WHOO 韩国宫廷护肤</a></li>
									<li><a href="#">ELIZABETH ARDEN 雅顿畅销护肤品</a></li>
									<li><a href="#">SK-II 日本殿堂级护肤品</a></li>
									<li><a href="#">REFA 风靡日本美容神器</a></li>
									<li><a href="#">秋季滋补佳品 保健品专场</a></li>
								</ul>
								<p><a href="#" class="look">查看所有活动</a></p>
							</div>
							<div class="smallnav_right">
								<h4>商品分类</h4>
								<ul>
									<li><a href="#">护肤</a></li>
									<li><a href="#">彩妆</a></li>
									<li><a href="#">美体</a></li>
									<li><a href="#">美发</a></li>
									<li><a href="#">男士</a></li>
									<li><a href="#">香氛</a></li>
									<li><a href="#">保健</a></li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<a href="#">家居</a>
						<div class="smallnav">
							<div class="smallnav_left">
								<h4>热门活动</h4>
								<ul>
									<li><a href="#">职场温馨小物件 专场</a></li>
									<li><a href="#">DOWNIA 澳洲家居&地毯(满减)</a></li>
									<li><a href="#">中秋佳节 床品特辑</a></li>
									<li><a href="#">利快 创意家居</a></li>
									<li><a href="#">LAYTEX & TOM KATE 泰国乳胶枕</a></li>
									<li><a href="#">德式 厨房</a></li>
									<li><a href="#">热卖 小家电</a></li>
									<li><a href="#">THERMOS 膳魔师专场</a></li>
								</ul>
								<p><a href="#" class="look">查看所有活动</a></p>
							</div>
							<div class="smallnav_right">
								<h4>商品分类</h4>
								<ul>
									<li><a href="#">摆件</a></li>
									<li><a href="#">厨具</a></li>
									<li><a href="#">卫浴</a></li>
									<li><a href="#">家电</a></li>
									<li><a href="#">床品</a></li>
									<li><a href="#">办公&礼品</a></li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<a href="#">婴童</a>
						<div class="smallnav">
							<div class="smallnav_left">
								<h4>热门活动</h4>
								<ul>
									<li><a href="#">REIMA  芬兰功能性童装专场</a></li>
									<li><a href="#">REIMA  芬兰功能性鞋靴配饰专场</a></li>
									<li><a href="#">欢乐周末 玩伴专场</a></li>
									<li><a href="#">BIBI  巴西进口女童专场</a></li>
									<li><a href="#">BIBI  巴西进口男童专场</a></li>
									<li><a href="#">全球大搜罗  母婴尖货场</a></li>
									<li><a href="#"> HAO  日本潮牌童装女童专场</a></li>
									<li><a href="#">HAO  日本潮牌童装男童专场</a></li>
								</ul>
								<p><a href="#" class="look">查看所有活动</a></p>
							</div>
							<div class="smallnav_right">
								<h4>商品分类</h4>
								<ul>
									<li><a href="#">服装</a></li>
									<li><a href="#">鞋履</a></li>
									<li><a href="#">其他</a></li>
									<li><a href="#">配饰</a></li>
									<li><a href="#">玩具</a></li>
									<li><a href="#">母婴</a></li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<a href="#">老佛爷奥莱</a>
						<div class="smallnav" style="width: 315px;">
							<div class="smallnav_left">
								<h4>热门活动</h4>
								<ul>
									<li><a href="#">老佛爷百货 女士裙装 夏日大降价</a></li>
									<li><a href="#">老佛爷百货  女士上装 夏日大降价</a></li>
									<li><a href="#">老佛爷百货  女士裤装 夏日大降价</a></li>
									<li><a href="#">老佛爷百货  女士鞋履 夏日大降价</a></li>
									<li><a href="#">老佛爷百货  女士包袋配饰夏日大降价</a></li>
									<li><a href="#">老佛爷百货 男士上装 夏日大降价</a></li>
									<li><a href="#">老佛爷百货 男士下装 夏日大降价</a></li>
									<li><a href="#">老佛爷百货 男士鞋履 夏日大降价</a></li>
								</ul>
								<p><a href="#" class="look">查看所有活动</a></p>
							</div>
						</div>
					</li>
					<li><a href="#">即将推出</a></li>
				</ul>
				<ul class="list_right">
					<li><a href="cart.html" target="_blank" class="sum">0</a></li>
					<li>|</li>
					<li><a href="cart.html" target="_blank">￥0.00</a></li>
					<div class="shopping">
						<div class="no_shopping">
							购物袋暂无商品
						</div>
						<a href="#"></a>
					</div>
				</ul>
			</div>
		</div>
		<div class="content">
			<div class="content_header">
				<ul>
					<li><a href="index.html">首页</a></li>
					<li><span>></span><a href="index.html">女士</a></li>
					<li><span>></span>TORY BURCH</li>
				</ul>
				<div class="countdown">
					<span class="timer">0天0小时0分0秒</span>
					<span class="countdown_word">活动剩余</span>
				</div>
			</div>
			<div class="title">
				<h2>TORY BURCH&nbsp;&nbsp;&nbsp;&nbsp;女士精品系列上新&nbsp;&nbsp;&nbsp;&nbsp;<span>2<span class="sale">折起</span></span></h2>
				<span class="collect"><span>+</span>收藏品牌</span>
			</div>
			<div class="story">
				<div class="background">
					<div class="story_content">
						<p class="gift">满688元全场免运（跨境商品除外）</p>
						<div class="brand_story">
							<h5>品牌故事</h5>
							<p>Tory Burch成立于2004 年2月，它是一个实际可行的时尚生活方式品牌，源于经典的美国运动时装风格，充满无拘无束的活力与感觉，其共混永恒的，经典的设计元素与现代时尚的感情。汤丽柏琦（Tory Burch）是一个实际可行的时尚生活方式品牌，源于经典的美国运动时装风格，充满无拘无束的活力与感觉，充分体现了行政总裁Tory Burch的个人风格和精神。她独具慧眼，将设计师的审美观与价值观在市场上取得平衡，创作出时尚又适合所有年龄女性穿着的时装与配饰。<a href="#">更多</a></p>
						</div>
					</div>
				</div>
			</div>
			<div class="choose">
				<span>已选条件：</span>
				<ul>
					<li>种类：平底鞋</li>
					<li>种类：手提包</li>
					<li>种类：运动户外</li>
					<li>种类：钱包/小型配件</li>
					<li>种类：靴子</li>
				</ul>
				<b>清空筛选条件</b>
			</div>
			<div class="type">	
				<p>种类：</p>
				<ul>
					<li><span></span>平底鞋</li>
					<li><span></span>手提包</li>
					<li><span></span>运动户外</li>
					<li><span></span>钱包/小型配件</li>
					<li><span></span>靴子</li>
				</ul>
			</div>
			<div class="product_query">
				<a href="#" class="sort sorter">默认排序</a>
				<a href="#" class="pirce sorter">价格</a>
				<div class="page">
					<h6>共<b>4</b>个商品</h6>
					<span class="_page">1/1</span>
					<span class="pre"></span>
					<span class="next"></span>
				</div>
			</div>
			<div class="contentDiv">
                <!--商品列表-->



					{% for good in goods %}

						<div class="product">
							<div class="product_img" >
								<a href="{% url 'App:goods' good.goodsid %}">
									<div class="product_label">{{ good.buyer }}</div>
									<img src="{{ good.src1 }}" title="{{ good.title }}" class="img_first"/>
									<img src="{{ good.src2 }}" title="{{ good.title }}" />
									<img src="{{ good.src3 }}" title="{{ good.title }}" />
								</a>
							</div>
							<div class="product_content">
								<p><a href="{% url 'App:goods' good.goodsid %}">{{ good.name }}</a></p>
								<p><a href="{% url 'App:goods' good.goodsid %}">{{ good.title }}</a></p>
								<p><span>{{ good.price }} </span><span>{{ good.original_price }}</span></p>
							</div>
							<div class="product_pic">
								<ul>
									<li><img src="{{ good.index1 }}"></li>
									<li><img src="{{ good.index2 }}"></li>
									<li><img src="{{ good.index3 }}"></li>
								</ul>
							</div>
						</div>
					{% endfor %}



                <!--商品列表-->


			</div>
		</div>
		<div class="footer">
			<div class="footer_center">
				<ul class="footer_ul1">
					<li><a href="#" class="a1">100%品牌授权正品</a></li>
					<li><a href="#" class="a2">满688免运费</a></li>
					<li><a href="#" class="a3">7天无条件退货</a></li>
					<li><a href="#" class="a4">超值折扣</a></li>
					<li><a href="#" class="a5">9点限时闪购</a></li>
					<li style="border: none;"><a href="#" class="a6">400-664-6698</a></li>
				</ul>
				<p class="footer_p1">
					<a href="#">关于魅力惠</a>
					<a href="#">加入我们</a>
					<a href="#">联系我们</a>
					<a href="#">使用帮助</a>
					<a href="#">使用规则</a>
					<a href="#">隐私声明</a>
					<a href="#">网站地图</a>
				</p>
				<p><span>COPYRIGHT©2016 杭州魅俪信息技术有限公司版权所有</span>浙ICP备16004860号-1 </p>
				<p>
					<a href="#"><img src="../static/img/guohui.png" /></a>
					<a href="#"><img src="../static/img/chengxin.png" /></a>
				</p>
			</div>
		</div>
	</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>用户登录页面</title>
		<link rel="icon" href="{% static 'img/love.png' %}" type="image/x-icon">
		<link rel="stylesheet" href="{% static 'css/login-register.css' %}" />
		<link rel="stylesheet" href="{% static 'css/jquery.idcode.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/login.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.idcode.js' %}" ></script>
	</head>
	<body>
		<div class="all">
			<div class="middle">
				<div class="register_header">
					<a href="index.html">
						<img src="{% static 'img/mei.png' %}" />
					</a>
				</div>
				<div class="register_content">
					<div class="register_in">
						<div class="newpeople">
							<h2>会员登录</h2>
							<p class="_login">没有账号 ? <a href="/register/">免费注册</a></p>
						</div>
						<div class="userinfo">
							<form action="/meilihui/login/" method="post">
								{% csrf_token %}
								<span>账户名:</span><input type="text" placeholder="请输入已注册的手机号" id="user" name="tel"/>
								<p class="remind" id="entry_user">请输入已注册的手机号</p>
								<p class="remind" id="entry_user_true">请输入正确的手机号</p>
								<span>密码:</span><input type="password" id="password" maxlength="20" name="password"/>
								<!--<span>验证码:</span><input type="text" class="code txtVerification" id="Txtidcode"/>-->
								<!--<span id="idcode"></span>-->
								<!--<p class="remind" id="entry_code">请输入验证码</p>-->
								<!--<p class="remind" id="entry_code_true">请输入正确验证码</p>-->
								<p class="remind" id="wrong">账号或密码错误</p>
								<input type="submit" value="会员登录" class="submit" id="login"/>
								<div>
									{% if error %}
            							<p id="err">{{ error }}</p>
        							{% endif %}
								</div>
								<p><span class="checkbox1" id="checkbox"></span>下次自动登录<a href="#"
																						 class="forget">忘记密码</a></p>
								<span>联名登录:</span><a href="#" class="weibo"></a><a href="#" class="zhifubao"></a>
							</form>
						</div>
						<div class="QR_code">
							<img src="{% static 'img/saomiao.jpg' %}" />
							<p>扫描二维码或发送短信<br />“MLH”到“12114”<br />下载APP尊享独家优惠</p>
						</div>
					</div>
				</div>
				<div class="footer_center">
					<ul class="footer_ul1">
						<li><a href="#" class="a1">100%品牌授权正品</a></li>
						<li><a href="#" class="a2">满688免运费</a></li>
						<li><a href="#" class="a3">7天无条件退货</a></li>
						<li><a href="#" class="a4">超值折扣</a></li>
						<li><a href="#" class="a5">9点限时闪购</a></li>
						<li style="border: none;"><a href="#" class="a6">400-664-6698</a></li>
					</ul>
					<p><span>COPYRIGHT©2016 杭州魅俪信息技术有限公司版权所有</span>浙ICP备16004860号-1 </p>
				</div>
			</div>
		</div>
	</body>
</html>

templates/orderinfo.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单信息</title>
    <link rel="stylesheet" href="/static/css/orderinfo.css">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
    <script type="text/javascript" src="/static/js/orderinfo.js"></script>
</head>
<body>
    <div class="orderinfo">
        <h3>订单号: {{ order.identifier }}</h3>
        <ul>
            {% for orderGoods in order.ordergoods_set.all %}
                <li>
                    <div class="content-wrapper">
                        <div class="img">
                            <img src="{{ orderGoods.goods.src1 }}" alt="">
                        </div>
                        <div class="detail">
                            <p class="name">
                                {{ orderGoods.goods.title }}
                            </p>
                            <p class="price">
                                ￥{{ orderGoods.goods.price }}
                            </p>
                            <p class="num">
                                x{{ orderGoods.number }}
                            </p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <button class="btn btn-success" id="pay" identifier="{{ order.identifier }}">付款</button>
    </div>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>
        {{}}
    <form action=""></form>
    {% if %}
    {% endif %}
    {% if %}
    {% endif %}
    {% for book in books %}

    {% endfor%}
    {% url  %}

    {% block %}

    {% endbolck %}




    </p>
</body>
</html>